#include "fpga_interface.h"


// clang-format off
const uint32_t fpga_lut[FPGA_OPCODE_IDX_COUNT * 4] = {
    LUT_NULL(FPGA_LUT_IDX_WR_SPI1),      
    LUT_NULL(FPGA_LUT_IDX_WR_SPI2),    
    LUT_NULL(FPGA_LUT_IDX_WR_DCU_OUT), 
    LUT_NULL(FPGA_LUT_IDX_WR_GENERIC_CMD),
    LUT_NULL(FPGA_LUT_IDX_WR_UART1),     
    LUT_NULL(FPGA_LUT_IDX_WR_UART2),   
    LUT_NULL(FPGA_LUT_IDX_WR_UART3),   
    LUT_NULL(FPGA_LUT_IDX_WR_UART4),
    LUT_NULL(FPGA_LUT_IDX_WR_MCASP_CFG),
    LUT_NULL(FPGA_LUT_IDX_WR_PPS_SEL),
    LUT_NULL(FPGA_LUT_IDX_WR_MST_CLK),

    [LUT_IDX(FPGA_LUT_IDX_RD_SAMPLE, 0)] = FLEXSPI_LUT_SEQ(LUT_CMD, kFlexSPI_4PAD, FPGA_OPCODE_RD_SAMPLE, LUT_ADDR, kFlexSPI_4PAD, LUT_DUMMY),
    [LUT_IDX(FPGA_LUT_IDX_RD_SAMPLE, 1)] = 0,
    [LUT_IDX(FPGA_LUT_IDX_RD_SAMPLE, 2)] = 0,
    [LUT_IDX(FPGA_LUT_IDX_RD_SAMPLE, 3)] = 0,

    LUT_NULL(FPGA_LUT_IDX_RD_SPI1),
    LUT_NULL(FPGA_LUT_IDX_RD_SPI2),
    LUT_NULL(FPGA_LUT_IDX_RD_UART1),
    LUT_NULL(FPGA_LUT_IDX_RD_UART2),
    LUT_NULL(FPGA_LUT_IDX_RD_UART3),
    LUT_NULL(FPGA_LUT_IDX_RD_UART4),
    LUT_NULL(FPGA_LUT_IDX_RD_SYNC_IN),
    LUT_NULL(FPGA_LUT_IDX_RD_MST_CLK)
};

// clang-format on
